### ISSUE TITLE
User account vs Organisation account?

### ISSUE THREAD

**Issue by RaoOfPhysics** [Libraccess/docs#2]
Should Libraccess be an organisation instead of a user?

[Guide](https://help.github.com/articles/converting-a-user-into-an-organization/)

**Comment by Libraccess** [comment]
Hi,

Yes surely - what does it entail? Thanks!
Clement Levallois
Assistant professor EMLYON
Markets & Innovation Department
http://www.clementlevallois.net

direct line: +33(0)4 7833 7725
mobile: +33(0)6 5908 3392
Skype and Twitter: @seinecle
________________________________________

**Comment by RaoOfPhysics** [comment]
You can check out [this official guide on converting a user account to an organisation](https://help.github.com/articles/converting-a-user-into-an-organization/). Essentially, you want to limit "user" accounts to individuals. Organisations can create repos, the users in those organisations can be given rights to merge pull requests etc.

**Comment by seinecle** [comment]
Just converted Libraccess into an organisation, thanks!
